# Generated by Django 5.2.6 on 2025-09-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='process',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
