# Generated by Django 5.2.6 on 2025-09-17 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_creator', '0002_alter_process_options_process_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='process_screenshots/')),
                ('order', models.PositiveIntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='process_creator.step')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
