# Generated by Django 5.2.6 on 2025-09-17 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_creator', '0003_stepimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='analysis',
            field=models.TextField(blank=True, help_text='AI-generated analysis and improvement suggestions'),
        ),
        migrations.AddField(
            model_name='process',
            name='analysis_instructions',
            field=models.TextField(blank=True, default='Analyze this process and provide:\n1. Current process assessment\n2. Identified inefficiencies\n3. Automation opportunities\n4. Programming solutions\n5. Efficiency gains and ROI\n6. Implementation recommendations', help_text='Instructions for AI analysis'),
        ),
        migrations.AddField(
            model_name='process',
            name='last_ai_update',
            field=models.DateTimeField(blank=True, help_text='Last time AI was used to update summary or analysis', null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of the process'),
        ),
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('summary', 'Summary Generation'), ('analysis', 'Process Analysis'), ('custom', 'Custom Analysis')], max_length=20)),
                ('prompt_sent', models.TextField(help_text='The prompt/instructions sent to AI')),
                ('response_received', models.TextField(help_text='The response received from AI')),
                ('tokens_used', models.PositiveIntegerField(blank=True, help_text='Number of tokens used', null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=6, help_text='Cost of this interaction', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interactions', to='process_creator.process')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
