# Generated by Django 5.2.6 on 2025-09-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_creator', '0004_process_analysis_process_analysis_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='summary_instructions',
            field=models.TextField(blank=True, default='Create a concise 2-3 sentence summary that captures the essence of this process, highlighting the key steps and purpose.', help_text='Instructions for AI summary generation'),
        ),
    ]
