# Generated by Django 4.2.13 on 2025-09-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_creator', '0005_process_summary_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinteraction',
            name='prompt_sent',
            field=models.TextField(help_text='The prompt/instructions sent'),
        ),
        migrations.AlterField(
            model_name='aiinteraction',
            name='response_received',
            field=models.TextField(help_text='The response received'),
        ),
        migrations.AlterField(
            model_name='process',
            name='analysis',
            field=models.TextField(blank=True, help_text='Generated analysis and improvement suggestions'),
        ),
        migrations.AlterField(
            model_name='process',
            name='analysis_instructions',
            field=models.TextField(blank=True, default='You are a senior operations analyst. You will receive a business process as input (steps, notes, and context). Produce a professional report titled "Training Analysis" that managers and frontline staff can act on.\nFollow these rules:\n- Write clearly and concisely; avoid jargon. Use confident, direct language.\n- Do NOT restate the steps as bullets. Summarize the process in flowing prose.\n- Use Markdown headings exactly as specified below.\n- Give specific, actionable recommendations with clear benefits and effort levels.\n- Where details are missing, make reasonable assumptions and state them briefly.\n=== INPUT START ===\n{PASTE PROCESS STEPS / NOTES / CONTEXT HERE}\n=== INPUT END ===\n=== OUTPUT FORMAT (Markdown) ===\n# Training Analysis\n## Executive Summary\nA 4–6 sentence overview of the process, the primary objective, the current state, and the most important recommended changes and expected benefits.\n## Process Narrative (Plain-Language Summary)\n6–10 sentences that narrate how the process works from start to finish. Use paragraph form only (no bullets). Emphasize flow, handoffs, tools used, approvals, and timing.\n## Assumptions\n- 2–5 short bullets listing key assumptions you made due to missing information.\n## Strengths\n- 4–8 bullets. Each bullet: what works well + why it matters (impact on quality, speed, cost, compliance, safety, or CX).\n## Weaknesses\n- 4–8 bullets. Each bullet: the issue + consequence (e.g., rework, delays, risk, cost).\n## Improvement Opportunities — Current System (No new software)\nProvide 5–10 specific, low-friction changes using existing tools, roles, and policies. For each item, use this format in one bullet:\n- **[Title]** — What to change (1–2 sentences). **Benefit:** expected outcome with a measurable indicator (e.g., "reduce cycle time by ~15%"). **Effort:** Low/Med/High. **Owner:** role. **Risk/Mitigation:** brief.\n## Immediate Application-Level Enhancements (Quick to implement in an app/workflow)\nProvide 3–7 changes that can be implemented quickly via simple configuration, scripts, forms, validations, templates, or notifications. For each item, use the same format:\n- **[Title]** — What to implement (1–2 sentences). **Benefit:** measurable. **Effort:** Low/Med/High. **Owner:** role. **Risk/Mitigation:** brief.\n## Implementation Roadmap\nOrganize recommendations into phases with rationale:\n- **Now (0–30 days):** 3–6 highest-ROI, low-effort actions.\n- **Next (30–90 days):** 3–6 medium-effort actions that compound earlier gains.\n- **Later (90+ days):** 2–4 higher-effort changes that deliver strategic value.\n## Metrics & Monitoring\nList 4–8 KPIs with target direction and cadence. For each KPI: **Name**, **Target/Direction**, **Data Source**, **Review Cadence** (e.g., weekly), **Owner**.\n## Risks & Mitigations\n3–6 material risks across people/process/tech/compliance and how to mitigate each.\n## Final Recommendation\nA 4–6 sentence closing paragraph summarizing the case for change, expected benefits, and the immediate next steps.\n=== STYLE GUARDRAILS ===\n- Professional tone. Tight sentences. No filler, no hype.\n- Use paragraph form for the narrative sections; bullets only where specified.\n- Quantify benefits or ranges when plausible. Avoid vague claims.\n- Do not include meta-commentary or instructions in the output.', help_text='Instructions for process analysis'),
        ),
        migrations.AlterField(
            model_name='process',
            name='last_ai_update',
            field=models.DateTimeField(blank=True, help_text='Last time summary or analysis was updated', null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='summary',
            field=models.TextField(blank=True, help_text='Generated summary of the process'),
        ),
        migrations.AlterField(
            model_name='process',
            name='summary_instructions',
            field=models.TextField(blank=True, default='You are given a list of steps, bullet points, or fragmented notes. Your task is to transform them into a single professional, coherent paragraph. Do not repeat the steps as a list. Instead, weave them into smooth, natural prose that reads as if written by a skilled professional writer. Maintain accuracy, logical flow, and clarity. The output must always be a polished paragraph summary, never a bullet list.', help_text='Instructions for summary generation'),
        ),
    ]
