# Generated by Django 4.2.13 on 2025-09-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_creator', '0006_alter_aiinteraction_prompt_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='process',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Module this process belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='process_creator.module'),
        ),
    ]
