# Generated by Django 4.2.13 on 2025-09-18 12:47

from django.db import migrations, models
import django.db.models.deletion
import process_creator.models


class Migration(migrations.Migration):

    dependencies = [
        ('process_creator', '0007_module_process_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='process_creator.step')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StepFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(upload_to=process_creator.models.step_file_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='process_creator.step')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
