# Generated by Django 5.2.6 on 2025-09-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_creator', '0008_steplink_stepfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepimage',
            name='substep_index',
            field=models.PositiveIntegerField(blank=True, help_text='0-based index of the bullet (substep) within step.details', null=True),
        ),
    ]
