# Generated by Django 5.2.6 on 2025-09-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_creator', '0009_stepimage_substep_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stepimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='steplink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
