# Generated by Django 5.2.6 on 2025-09-24 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_creator', '0011_processtemplate_job_jobstep_templatestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='template_version_at_create',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='JobSubtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='process_creator.jobstep')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('job_step', 'order')},
            },
        ),
    ]
