# Generated by Django 5.2.6 on 2025-09-24 13:59

import django.db.models.deletion
import process_creator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_creator', '0012_job_template_version_at_create_jobsubtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStepImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask_index', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=process_creator.models.job_step_image_upload_path)),
                ('order', models.PositiveIntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='process_creator.jobstep')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
