# Generated by Django 5.2.6 on 2025-09-25 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_creator', '0013_jobstepimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStepAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='job_attachments/')),
                ('original_name', models.CharField(help_text='Original filename', max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('subtask_index', models.PositiveIntegerField(blank=True, help_text='0-based index of the bullet (subtask) within job_step.details', null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('pdf_preview', models.FileField(blank=True, help_text='Converted PDF for inline viewing', null=True, upload_to='job_attachments/previews/')),
                ('conversion_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='process_creator.jobstep')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
