# Generated by Django 4.2.7 on 2025-09-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appaccess',
            name='app_name',
            field=models.CharField(choices=[('main', 'Main Dashboard'), ('theme', 'Theme Management'), ('settings', 'Settings'), ('account', 'Account Management'), ('project', 'Project Management'), ('approval_prints', 'Approval Prints'), ('product_configuration', 'Product Configuration'), ('messages', 'Messages'), ('suggestions', 'Suggestions')], max_length=50, unique=True),
        ),
    ]
