# Generated by Django 5.2.6 on 2025-09-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_alter_appaccess_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appaccess',
            name='app_name',
            field=models.CharField(choices=[('main', 'Main Dashboard'), ('theme', 'Theme Management'), ('flow_calc', 'Flow Calculator'), ('settings', 'Settings'), ('account', 'Account Management'), ('project', 'Project Management'), ('approval_prints', 'Approval Prints'), ('product_configuration', 'Product Configuration'), ('user_messages', 'Messages'), ('suggestions', 'Suggestions'), ('prints_to_customer', 'Prints to Customer'), ('long_lead_release', 'Long Lead Release'), ('drafting_queue', 'Drafting Queue'), ('engineering_review_and_release', 'Engineering Review and Release'), ('release_to_purchasing', 'Release to Purchasing'), ('process_creator', 'Process Creator')], max_length=50, unique=True),
        ),
    ]
