# Generated by Django 4.2.7 on 2025-09-16 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Project description')),
                ('start_date', models.DateField(help_text='Project start date')),
                ('duration_days', models.PositiveIntegerField(help_text='Total project duration in days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flow Project',
                'verbose_name_plural': 'Flow Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Step name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Step description')),
                ('duration_days', models.PositiveIntegerField(help_text='Step duration in days')),
                ('start_date', models.DateField(blank=True, help_text='Step start date (calculated)', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Step end date (calculated)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependencies', models.ManyToManyField(blank=True, help_text='Steps that must complete before this step starts', related_name='dependent_steps', to='flow_calc.flowstep')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='flow_calc.flowproject')),
            ],
            options={
                'verbose_name': 'Flow Step',
                'verbose_name_plural': 'Flow Steps',
                'ordering': ['start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FlowCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('total_duration_days', models.PositiveIntegerField(help_text='Total calculated project duration')),
                ('is_valid', models.BooleanField(default=True, help_text='Whether the calculation is valid')),
                ('error_message', models.TextField(blank=True, help_text='Error message if calculation failed')),
                ('critical_path_steps', models.ManyToManyField(blank=True, related_name='critical_calculations', to='flow_calc.flowstep')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculation', to='flow_calc.flowproject')),
            ],
            options={
                'verbose_name': 'Flow Calculation',
                'verbose_name_plural': 'Flow Calculations',
            },
        ),
    ]
