# Generated by Django 4.2.7 on 2025-09-16 18:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_subflows', to=settings.AUTH_USER_MODEL)),
                ('main_flow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subflows', to='flow.flowstep')),
            ],
            options={
                'verbose_name': 'Sub Flow',
                'verbose_name_plural': 'Sub Flows',
                'ordering': ['main_flow_step', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubFlowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(help_text='Order in the subflow (1, 2, 3...)')),
                ('estimated_duration', models.DurationField(help_text='Estimated time to complete')),
                ('is_required', models.BooleanField(default=True, help_text='Must this step be completed?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='flow.subflow')),
            ],
            options={
                'verbose_name': 'Sub Flow Step',
                'verbose_name_plural': 'Sub Flow Steps',
                'ordering': ['subflow', 'order'],
                'unique_together': {('subflow', 'order')},
            },
        ),
        migrations.CreateModel(
            name='SubFlowDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('finish_to_start', 'Finish to Start'), ('start_to_start', 'Start to Start'), ('finish_to_finish', 'Finish to Finish'), ('start_to_finish', 'Start to Finish')], default='finish_to_start', max_length=20)),
                ('lag_time', models.DurationField(default=datetime.timedelta(0), help_text='Time delay between steps')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successors', to='flow.subflowstep')),
                ('subflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='flow.subflow')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessors', to='flow.subflowstep')),
            ],
            options={
                'verbose_name': 'Sub Flow Dependency',
                'verbose_name_plural': 'Sub Flow Dependencies',
                'unique_together': {('predecessor', 'successor')},
            },
        ),
        migrations.CreateModel(
            name='ProjectSubFlowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('target_completion_date', models.DateTimeField(blank=True, null=True)),
                ('actual_completion_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subflow_steps', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subflow_steps', to='flow.project')),
                ('subflow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_instances', to='flow.subflowstep')),
            ],
            options={
                'verbose_name': 'Project Sub Flow Step',
                'verbose_name_plural': 'Project Sub Flow Steps',
                'ordering': ['subflow_step__order'],
                'unique_together': {('project', 'subflow_step')},
            },
        ),
    ]
